from __future__ import annotations

import json
import unittest
from pathlib import Path

from cachexia_poc.config import load_simulation_config

ROOT = Path(__file__).resolve().parents[1]


class ConfigurationTests(unittest.TestCase):
    def test_browser_config_is_generated_from_canonical_json(self):
        browser_text = (ROOT / "prototype" / "simulation-config.js").read_text(
            encoding="utf-8"
        )
        prefix = (
            '"use strict";\n'
            "// Generated by scripts/sync_browser_config.py; do not edit manually.\n"
            "window.SIMULATION_CONFIG = Object.freeze("
        )
        self.assertTrue(browser_text.startswith(prefix))
        self.assertTrue(browser_text.endswith(");\n"))
        browser_config = json.loads(browser_text[len(prefix) : -3])
        self.assertEqual(browser_config, load_simulation_config())

    def test_schema_pins_each_outcome_horizon(self):
        schema = json.loads(
            (ROOT / "docs" / "schema.v1.json").read_text(encoding="utf-8")
        )
        self.assertEqual(
            schema["$defs"]["outcome3m"]["allOf"][1]["properties"][
                "horizon_months"
            ]["const"],
            3,
        )
        self.assertEqual(
            schema["$defs"]["outcome6m"]["allOf"][1]["properties"][
                "horizon_months"
            ]["const"],
            6,
        )

    def test_supplied_simulation_multipliers_are_centralized(self):
        config = load_simulation_config()
        relationships = config["simulation_relationships"]
        self.assertEqual(
            relationships["stage_risk_multipliers"],
            {"I": 1.0, "II": 1.2, "III": 1.5, "IV": 2.0, "unknown": 1.0},
        )
        self.assertEqual(
            relationships["cancer_risk_multipliers"]["pancreatic"], 2.0
        )
        self.assertEqual(
            relationships["cancer_risk_multipliers"]["breast"], 1.0
        )
        self.assertEqual(
            config["definitions"]["precachexia_rule_status"],
            "provisional_option_b_pending_clinical-reviewer_clinical-reviewer_review",
        )


if __name__ == "__main__":
    unittest.main()
