from __future__ import annotations

import json
import unittest
from pathlib import Path

from cachexia_poc.config import load_simulation_config

ROOT = Path(__file__).resolve().parents[1]


class ConfigurationTests(unittest.TestCase):
    def test_browser_config_is_generated_from_canonical_json(self):
        browser_text = (ROOT / "prototype" / "simulation-config.js").read_text(
            encoding="utf-8"
        )
        prefix = (
            '"use strict";\n'
            "// Generated by scripts/sync_browser_config.py; do not edit manually.\n"
            "window.SIMULATION_CONFIG = Object.freeze("
        )
        self.assertTrue(browser_text.startswith(prefix))
        self.assertTrue(browser_text.endswith(");\n"))
        browser_config = json.loads(browser_text[len(prefix) : -3])
        self.assertEqual(browser_config, load_simulation_config())

    def test_schema_pins_each_outcome_horizon(self):
        schema = json.loads(
            (ROOT / "docs" / "schema.v1.json").read_text(encoding="utf-8")
        )
        self.assertEqual(
            schema["$defs"]["outcome3m"]["allOf"][1]["properties"][
                "horizon_months"
            ]["const"],
            3,
        )
        self.assertEqual(
            schema["$defs"]["outcome6m"]["allOf"][1]["properties"][
                "horizon_months"
            ]["const"],
            6,
        )
        self.assertIn("Migration from v1.0", schema["$comment"])
        self.assertIn("follow_up_appetite_observations", schema["required"])
        self.assertEqual(
            schema["$defs"]["categoryBase"]["properties"]["category"]["enum"],
            ["low", "moderate", "high", None],
        )
        self.assertEqual(
            schema["$defs"]["categoryBase"]["properties"]["target_outcome"][
                "const"
            ],
            "not_defined_pending_clinical_review",
        )
        self.assertFalse(
            schema["$defs"]["outcomeBase"]["properties"][
                "fearon_classification"
            ]["const"]
        )
        self.assertIn(
            "outcome_interval_days",
            schema["$defs"]["outcomeBase"]["required"],
        )
        subtype_rule = schema["allOf"][0]
        self.assertEqual(
            subtype_rule["then"]["properties"]["cancer_subtype"]["enum"],
            ["SCLC", "NSCLC", "unknown"],
        )
        self.assertEqual(
            subtype_rule["else"]["properties"]["cancer_subtype"]["const"],
            "not applicable",
        )
        serialized = json.dumps(schema).casefold()
        self.assertNotIn('"probability"', serialized)
        self.assertNotIn('"score"', serialized)

    def test_supplied_simulation_multipliers_are_centralized(self):
        config = load_simulation_config()
        relationships = config["simulation_relationships"]
        self.assertEqual(
            relationships["stage_risk_multipliers"],
            {"I": 1.0, "II": 1.2, "III": 1.5, "IV": 2.0, "unknown": 1.0},
        )
        self.assertEqual(
            relationships["cancer_risk_multipliers"]["pancreatic"], 2.0
        )
        self.assertEqual(
            relationships["cancer_risk_multipliers"]["breast"], 1.0
        )
        self.assertEqual(
            config["definitions"]["precachexia_rule_status"],
            "provisional_option_b_pending_clinical_review",
        )
        self.assertFalse(
            config["definitions"]["fearon_sarcopenia_branch_enabled"]
        )
        self.assertEqual(
            config["definitions"]["sarcopenia_status"],
            "future_use_pending_clinical_definition",
        )
        self.assertEqual(
            config["illustrative_category_model"]["output_contract"]["categories"],
            ["low", "moderate", "high"],
        )
        self.assertEqual(
            config["illustrative_category_model"]["output_contract"][
                "target_outcome"
            ],
            "not_defined_pending_clinical_review",
        )
        self.assertEqual(
            config["population_scope"]["eligibility_status"],
            "not_defined_pending_clinical_review",
        )
        self.assertEqual(config["population_scope"]["agreed_exclusions"], [])


if __name__ == "__main__":
    unittest.main()
