#!/usr/bin/env python3
"""Generate the browser's immutable config artifact from the canonical JSON."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
source = ROOT / "config" / "simulation_assumptions.v1.json"
target = ROOT / "prototype" / "simulation-config.js"

with source.open(encoding="utf-8") as handle:
    config = json.load(handle)

payload = json.dumps(config, indent=2, sort_keys=True)
target.write_text(
    '"use strict";\n'
    "// Generated by scripts/sync_browser_config.py; do not edit manually.\n"
    f"window.SIMULATION_CONFIG = Object.freeze({payload});\n",
    encoding="utf-8",
)
print(f"Synced {source.relative_to(ROOT)} -> {target.relative_to(ROOT)}")
