"use strict";
// Generated by scripts/sync_browser_config.py; do not edit manually.
window.SIMULATION_CONFIG = Object.freeze({
  "cohort": {
    "age": {
      "maximum": 95,
      "minimum": 18,
      "triangular_mode": 65
    },
    "appetite_unknown_probability": 0.1,
    "bmi": {
      "maximum": 45,
      "minimum": 15,
      "triangular_mode": 24
    },
    "cancer_type_probabilities": {
      "breast": 0.09,
      "colorectal": 0.13,
      "gastric": 0.08,
      "head and neck": 0.1,
      "hepatobiliary": 0.08,
      "lung": 0.18,
      "oesophageal": 0.08,
      "other solid tumour": 0.07,
      "pancreatic": 0.12,
      "prostate": 0.07
    },
    "deliberate_edge_case_count": 8,
    "ecog_probabilities": {
      "0": 0.1425,
      "1": 0.38,
      "2": 0.285,
      "3": 0.114,
      "4": 0.0285,
      "unknown": 0.05
    },
    "future_horizon_months": [
      3,
      6
    ],
    "height_cm": {
      "female": {
        "maximum": 190,
        "mean": 162,
        "minimum": 140,
        "sd": 7
      },
      "male": {
        "maximum": 200,
        "mean": 176,
        "minimum": 150,
        "sd": 7
      },
      "unknown": {
        "maximum": 200,
        "mean": 169,
        "minimum": 140,
        "sd": 9
      }
    },
    "historical_weight_kg": {
      "maximum": 160,
      "minimum": 25
    },
    "history_month_offsets": [
      -6,
      -3
    ],
    "insufficient_history_probability": 0.12,
    "lung_subtype_probabilities": {
      "NSCLC": 0.75,
      "SCLC": 0.25
    },
    "prediction_date_cycle_days": 60,
    "prediction_date_start": "2026-01-15",
    "sarcopenia_probabilities": {
      "no": 0.55,
      "unknown": 0.3,
      "yes": 0.15
    },
    "sex_probabilities": {
      "female": 0.49,
      "male": 0.49,
      "unknown": 0.02
    },
    "stage_probabilities": {
      "I": 0.1,
      "II": 0.18,
      "III": 0.32,
      "IV": 0.35,
      "unknown": 0.05
    },
    "weight_kg": {
      "maximum": 150,
      "minimum": 35
    }
  },
  "definitions": {
    "days_per_month": 30.4375,
    "fearon_bmi_exclusive": 20.0,
    "fearon_sarcopenia_branch_enabled": true,
    "fearon_weight_loss_conditional_exclusive": 2.0,
    "fearon_weight_loss_primary_exclusive": 5.0,
    "horizon_boundary": "inclusive calendar date",
    "precachexia_lower_weight_loss_percent_exclusive": 1.0,
    "precachexia_rule_status": "provisional_option_b_pending_clinical-reviewer_clinical-reviewer_review",
    "precachexia_upper_weight_loss_percent_inclusive": 5.0,
    "risk_missing_predictor_policy": "withhold",
    "trajectory_epsilon_percent": 0.5
  },
  "edge_cases": {
    "baseline_weight_gain_percent": 3.0,
    "bmi_boundary_height_cm": 170.0,
    "bmi_boundary_value": 20.0,
    "limited_weight_loss_percent": 3.0,
    "supported_cachexia_weight_loss_percent": 6.0,
    "weight_loss_lower_boundary_percent": 2.0,
    "weight_loss_upper_boundary_percent": 5.0
  },
  "metadata": {
    "config_version": "1.0.0",
    "clinical-reviewer_confirmation_status": "pending",
    "purpose": "Synthetic research-only proof of concept",
    "source_sheet": "Prototype 1_agreed predictors",
    "source_workbook": "Data Extraction_literature review_20260728.xlsx",
    "warning": "Every distribution, coefficient, probability, multiplier and threshold in this file is a simulation assumption, not a validated clinical effect."
  },
  "risk_outputs": {
    "age_threshold_exclusive": 55,
    "band_thresholds": {
      "high_lower_inclusive": 0.6,
      "low_upper_exclusive": 0.3
    },
    "six_month": {
      "age_over_55": 0.3,
      "appetite": {
        "no": 0.0,
        "unknown": 0.15,
        "yes": 0.8
      },
      "baseline_weight_loss_per_percent": 0.15,
      "cancer_type_multiplier": 1.0,
      "ecog": {
        "0": -0.25,
        "1": 0.0,
        "2": 0.4,
        "3": 0.8,
        "4": 1.1,
        "unknown": 0.0
      },
      "intercept": -1.45,
      "low_bmi_under_20": 0.5,
      "stage": {
        "I": 0.0,
        "II": 0.2,
        "III": 0.5,
        "IV": 1.0,
        "unknown": 0.0
      }
    },
    "three_month": {
      "age_over_55": 0.25,
      "appetite": {
        "no": 0.0,
        "unknown": 0.15,
        "yes": 0.75
      },
      "baseline_weight_loss_per_percent": 0.13,
      "cancer_type_multiplier": 1.0,
      "ecog": {
        "0": -0.3,
        "1": 0.0,
        "2": 0.35,
        "3": 0.7,
        "4": 1.0,
        "unknown": 0.0
      },
      "intercept": -2.0,
      "low_bmi_under_20": 0.45,
      "stage": {
        "I": 0.0,
        "II": 0.2,
        "III": 0.5,
        "IV": 1.0,
        "unknown": 0.0
      }
    }
  },
  "simulation_relationships": {
    "appetite_yes_latent_multiplier": 0.8,
    "appetite_yes_logit_intercept": -1.0,
    "cancer_risk_multipliers": {
      "breast": 1.0,
      "colorectal": 1.3,
      "gastric": 1.8,
      "head and neck": 1.6,
      "hepatobiliary": 2.0,
      "lung": 1.6,
      "oesophageal": 1.8,
      "other solid tumour": 1.0,
      "pancreatic": 2.0,
      "prostate": 1.0
    },
    "ecog_latent_points": {
      "0": -0.8,
      "1": -0.3,
      "2": 0.4,
      "3": 0.9,
      "4": 1.3,
      "unknown": 0.0
    },
    "future_monthly_loss_percent_intercept": 0.15,
    "future_monthly_loss_percent_latent_multiplier": 0.42,
    "future_monthly_loss_percent_random_sd": 0.35,
    "historical_monthly_loss_percent_intercept": 0.0,
    "historical_monthly_loss_percent_latent_multiplier": 0.22,
    "latent_random_sd": 0.45,
    "latent_score_maximum": 3.0,
    "latent_score_minimum": -2.0,
    "monthly_loss_percent_maximum": 2.5,
    "monthly_loss_percent_minimum": -1.0,
    "six_month_increment_multiplier": 1.0,
    "stage_risk_multipliers": {
      "I": 1.0,
      "II": 1.2,
      "III": 1.5,
      "IV": 2.0,
      "unknown": 1.0
    }
  }
});
